settings:
  enabled: true

  # Если true - ники проверяются без учёта регистра
  ignore-name-case: true

  kick-message: "&cВход запрещён. Этот ник не привязан к вашему IP."

allowed:
  "128.133.217.195":
    - "Zloba_"
  "128.123.133.177":
    - "jsdhgao"
  "138.13.153.45":
    - "rocko82"